ALTER TABLE `CUSTOMER`
  ADD INDEX idx_customer_user_id (user_id),
  ADD CONSTRAINT fk_customer_user
    FOREIGN KEY (user_id) REFERENCES auth_user(id)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- Insert 10 users into auth_user
-- Password hashes generated by Django for passwords 'user1' ... 'user10'
-- 
INSERT INTO `auth_user` (
    password, last_login, is_superuser, username,
    first_name, last_name, email,
    is_staff, is_active, date_joined
) VALUES
('pbkdf2_sha256$1000000$RiWhm3agStyCcbeEGx0h3X$xaDhoqmdHSTO+vCIjUbNLjhIPZaIeKwTu6DI5v/atXA=',NULL, 1, 'admin', 'admin', 'staff', 'admin@gmail.com',1, 1, NOW()),
('pbkdf2_sha256$1000000$Fn0RZNRxwR9BLjcTNEaQqg$vOYXITcbC2NXneAhSk8vXV7F3tQ+SoeJ8w8RkaTyXbQ=', NULL, 0, 'user1',  'Todd',    'Sims',    'todd.sims@email.com',         0, 1, NOW()),
('pbkdf2_sha256$1000000$Vf5uTFBUG9nxzdATuvav0X$wzzEv5e6LswUo7VmNEhnV8rVAju41K5+iDHdVbMqTkw=', NULL, 0, 'user2',  'Robin',   'Harris',  'robin.harris@yahoo.com',      0, 1, NOW()),
('pbkdf2_sha256$1000000$4V1koRe2V5qSyzsU1fbwGb$j3BWDqDbobiWhiEvpX69SzeVRplCeQn2oHaIxZSXGhs=', NULL, 0, 'user3',  'Nancy',   'Deleon',  'nancy.deleon@hotmail.com',    0, 1, NOW()),
('pbkdf2_sha256$1000000$RZhoi9d7lRqMbfkukNWOdc$AVjmRndXuPuVsYw3UteT8l+OZgOnQMngafQVR+JcNrE=', NULL, 0, 'user4',  'Raymond', 'Miller',  'raymond.miller@email.com',    0, 1, NOW()),
('pbkdf2_sha256$1000000$vgpf7yLkYpi43BGGaU4HKU$VxmhyCdN4mm/0DSKUOmO67irkY6lXMx9X8U3LkVSG0M=', NULL, 0, 'user5',  'Alyssa',  'Jackson', 'alyssa.jackson@gmail.com',    0, 1, NOW()),
('pbkdf2_sha256$1000000$tR52LxJ845Py2ZwGDZnqCZ$kzpchf+tULmaUaN8gB5k9qTBa70mecd1BMdYKn5mXrI=', NULL, 0, 'user6',  'Hailey',  'Webb',    'hailey.webb@hotmail.com',     0, 1, NOW()),
('pbkdf2_sha256$1000000$YJmd2XXGv9hQKFvhn6xlBq$oHUkbF54rnv1uSTtvWjhFb68I9kJVAQCsShtp84c2PE=', NULL, 0, 'user7',  'Jessica', 'Irwin',   'jessica.irwin@email.com',     0, 1, NOW()),
('pbkdf2_sha256$1000000$aGRWKyw6JwCHR8wEswoFDh$Tx+Cvuj0XdlI6wUV8qwbEmPPmNEl3RjbY7P9QxcNgaE=', NULL, 0, 'user8',  'Tina',    'Rhodes',  'tina.rhodes@email.com',       0, 1, NOW()),
('pbkdf2_sha256$1000000$HR54YSziabH3tSwIALMsFH$9WaBzwX2pjeov8NgoY/F2aUWMVaKnFdTx6iIsQq2srs=', NULL, 0, 'user9',  'Anne',    'Johnson', 'anne.johnson@hotmail.com',    0, 1, NOW()),
('pbkdf2_sha256$1000000$Vmp6ivWTXOVhaiy6SOnk3q$JaFxHuTe7gRXgtCGRbtpp2Jn6271Lm2Ueqs+ZnvuhWo=', NULL, 0, 'user10', 'Rachel',  'Wheeler', 'rachel.wheeler@email.com',    0, 1, NOW());


-- Link each of the first 10 customers to a user
UPDATE CUSTOMER SET user_id = (SELECT id FROM auth_user WHERE username = 'user1') WHERE customer_id = 11;
UPDATE CUSTOMER SET user_id = (SELECT id FROM auth_user WHERE username = 'user2') WHERE customer_id = 12;
UPDATE CUSTOMER SET user_id = (SELECT id FROM auth_user WHERE username = 'user3') WHERE customer_id = 13;
UPDATE CUSTOMER SET user_id = (SELECT id FROM auth_user WHERE username = 'user4') WHERE customer_id = 14;
UPDATE CUSTOMER SET user_id = (SELECT id FROM auth_user WHERE username = 'user5') WHERE customer_id = 15;
UPDATE CUSTOMER SET user_id = (SELECT id FROM auth_user WHERE username = 'user6') WHERE customer_id = 16;
UPDATE CUSTOMER SET user_id = (SELECT id FROM auth_user WHERE username = 'user7') WHERE customer_id = 17;
UPDATE CUSTOMER SET user_id = (SELECT id FROM auth_user WHERE username = 'user8') WHERE customer_id = 18;
UPDATE CUSTOMER SET user_id = (SELECT id FROM auth_user WHERE username = 'user9') WHERE customer_id = 19;
UPDATE CUSTOMER SET user_id = (SELECT id FROM auth_user WHERE username = 'user10') WHERE customer_id = 20;